[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[registry]
url = "https://anchor.projectserum.com"

[workspace]
members = ["programs/protocol"]

[programs.localnet]
protocol = "HTBzkQCWc2sbkn5WmLkPmQKKotaeeWgZ3RSD4Eg3f1MS"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000"