[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
protocol = "HTBzkQCWc2sbkn5WmLkPmQKKotaeeWgZ3RSD4Eg3f1MS"
puppet = "8KQzCc22ZqGLPoipqRhYvkQtHJw6nY1NxrrGy8JLz1jC"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/protocol", "programs/puppet"]

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000"

[test.validator]
[[test.genesis]]
address = "HyaB3W9q6XdA5xwpU4XnSZV94htfmbmqJXZcEbRaJutt"
program = "invariant.so"