[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
protocol = "HTBzkQCWc2sbkn5WmLkPmQKKotaeeWgZ3RSD4Eg3f1MS"
invariant = "CsT21LCRqBfh4SCcNZXtWjRZ6xvYKvdpEBaytCVmWnVJ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/protocol", "programs/invariant"]

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000"
