name: test protocol

permissions:
  contents: read

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  solana_version: 1.18.18
  anchor_version: 0.29.0

jobs:
  install:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./protocol
    strategy:
      matrix:
        case:
          [
            'npm run test:init',
            'npm run test:token',
            'npm run test:invoke',
            'npm run test:init-lp-pool',
            'npm run test:math'
          ]
    steps:
      - uses: actions/checkout@v4
      - name: test
        run: |
          echo "${{ matrix.case }}"
      - uses: actions/cache@v3
        name: Cache Cargo registry + index
        id: cache-anchor
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: cargo-${{ runner.os }}-v0000-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions/cache@v4
        name: Cache Solana Tool Suite
        id: cache-solana
        with:
          path: |
            ~/.cache/solana/
            ~/.local/share/solana/
          key: solana-${{ runner.os }}-v0000-${{ env.solana_version }}
      - uses: actions/cache@v4
        name: Cache target folder
        id: cache-programs
        with:
          path: |
            ./target
          key: solana-${{ runner.os }}-v0000-${{ hashFiles('**/programs/**/*.rs') }}-${{ hashFiles('**/programs/**/*.toml') }}
      - uses: actions/cache@v4
        name: Cache Node Modules
        id: cache-node-modules
        with:
          path: |
            ~/.npm/
            ./node_modules
          key: npm-${{ runner.os }}-v0000-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: rustup defualt nightly
          override: true
      - name: install global mocha
        run: |
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          npm install -g mocha
          npm install -g ts-mocha
          npm install -g typescript
          npm install -g @project-serum/anchor
          ts-mocha -h
      - name: install essential
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config build-essential libudev-dev
      - name: install solana
        if: steps.cache-solana.outputs.cache-hit != 'true'
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/v${{ env.solana_version }}/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          solana --version
      - name: setup solana
        run: |
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          solana --version
          solana-keygen new -o "$HOME/.config/solana/id.json" --no-passphrase --silent
      - name: install Anchor
        if: steps.cache-anchor.outputs.cache-hit != 'true'
        run: |
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          cargo install --git https://github.com/project-serum/anchor --tag v${{ env.anchor_version }}  anchor-cli --locked
      - name: build programs
        run: |
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          anchor build
      - name: install
        run: |
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          npm install
      - name: build invariant sdk & staker sdk
        run: |
          npm run build:all
      - name: test
        run: |
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          ${{ matrix.case }}
